config/routes.rb
Ideia::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  root to: "index#index"

  resources :journals

  resources :adoptions do
    member do
          get "journal"
    end
   end

  resources :categories do
    member do
      get "theories"
      get "tips"
    end
  end

  resources :admins

  resources :users

  resources :theories do
     member do
          get "adopt"
          get "abandon"
    end
   end

  resources :tips

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  #get
  get 'theories/adopted'
  get 'users/validated'
  get 'index/index'
  get 'index/about'
  get 'users/message_return'
  get 'login/login'
  get 'login/logout'
  #post
  post 'login/login'
  post 'login/logout'
  post 'register/new'
  post '/vote/:theory_id/:vote' => 'votes#vote'
  post '/favorite/:theory_id/' => 'favorites#check'
  post '/votes/:tip_id/:vote' => 'votes#tipv'
  post '/favorites/:tip_id/' => 'favorites#tipf'
  post '/theories/search' => 'theories#search'

  match 'entrar' => 'login#login'
  match 'sair' => 'login#logout'
  match '/users/:token/confirm' => 'users#confirm'
  match '/users/:id/send' => 'users#sendMail'
  match '/adoptions/new/:theory' => 'adoptions#new'
  match '/journals/new/:id' => 'journals#new'
  match '*a', to: 'errors#routing'

end

app/models/adoption.rb
class Adoption < ActiveRecord::Base
  attr_accessible :rating, :theory_id, :user_id

  validate :theory_id, presence: true
  validate :user_id, presence: true
  validate :rating

  belongs_to :theory
  belongs_to :user
  has_many  :journals, dependent: :destroy
end

app/controllers/adoptions_controller.rb
# encoding: utf-8
class AdoptionsController < ApplicationController
  layout 'empty'
  respond_to :html

  before_filter :logged?, except: [:index, :show]
  before_filter :admin?, except: [:journal]

  def index
    if session[:kind] == 2
      @adoptions = Adoption.all
      respond_with @adoptions
    else
      redirect_to "/404"
    end
  end

  def show
    @adoption = Adoption.find(params[:id]) rescue nil
    if @adoption
      respond_with @adoption
    else
      redirect_to "/404"
    end
  end

  def new
    @adoption = Adoption.new
    respond_with @adoption
  end

  def edit
    @adoption = Adoption.find(params[:id]) rescue nil
    if @adoption
      respond_with @adoption
    else
      redirect_to "/404"
    end
  end

  def create
    @adoption = Adoption.new(params[:adoption])
    flash[:notice]="Adotado com sucesso!" if @adoption.save
    respond_with @adoption
  end

  def update
    @adoption = Adoption.find(params[:id])
    flash[:notice]="Dados atualizados com sucesso!" if @adoption.update_attributes(params[:adoption])
    respond_with @adoption
  end

  def destroy
    @adoption = Adoption.find(params[:id])
    @adoption.destroy
    respond_with @adoption
  end

  def journal
    @adoption = Adoption.find(params[:id])
    @journals = @adoption.journals.page(params[:page]).per(10)
  end
end

app/views/adoptions/_form.html.haml
= form_for @adoption do |f|
  - if @adoption.errors.any?
    #error_explanation
      %h2= "#{pluralize(@adoption.errors.count, "error")} prohibited this adoption from being saved:"
      %ul
        - @adoption.errors.full_messages.each do |msg|
          %li= msg

  .field
    %p#label Selecione o Usuário
    = f.collection_select :theory_id, Theory.all, :id , :title, name: 'adoption[theory_id]'
  .field
    %p#label Selecione o Usuário
    = f.collection_select :user_id, User.all, :id , :name, name: 'adoption[user_id]'
  .actions
    = f.submit 'Salvar', class: 'enter'

app/views/adoptions/edit.html.haml
.userNew
  .data
    .greetings
      %h2 Atualização de adoção!
    %p#notice= notice
    .content
      = render 'form'

app/views/adoptions/index.html.haml
.tableArea
  .data
    %h1 Adoções
    .adminPanel
      .buttons
        .button
          = link_to 'Nova Adoção', new_adoption_path
    %table.tables
      %thead
        %tr
          %th ID T
          %th Ideia
          %th ID U
          %th Usuário
          %th
          %th
          %th
      %tbody
        - @adoptions.each do |adoption|
          %tr
            %td= adoption.theory_id
            %td= adoption.theory.title
            %td= adoption.user_id
            %td= adoption.user.name
            %td= link_to 'Mostrar', adoption
            %td= link_to 'Editar', edit_adoption_path(adoption)
            %td= link_to 'Apagar', adoption, :method => :delete, :data => { :confirm => 'Tem certeza?' }

app/views/adoptions/journal.html.haml
.tableArea
  .data
    %h1= "Diario de " + @adoption.user.name + ": " + @adoption.theory.title + "."
    - @journals.each do |journal|
      .greetings#journal
        %h1= journal.created_at.strftime("%d/%m/%Y")
        .content
          .image
            -if journal.image
              %img.JournalImage{src: "#{journal.image.to_s}"}
            -else
              %img.JournalImage{src: "/assets/no-image-found.png"}
          .desc
            %h2= truncate(journal.description, length: 500)
        -if journal.adoption.user.id == session[:id] || session[:kind] == 2
          .adminPanel
            .buttons
              .button
                =link_to 'Editar', edit_journal_path(journal)
              .button
                =link_to 'Apagar', journal, :method => :delete, :data => { :confirm => 'Tem certeza?' }

      %center
        -if @journals.size < 1
          %h1 Ainda não existem postagens, vamos lá crie uma !!!
        %br
        =link_to "+ Nota", "/journals/new/#{@adoption.id}"
        |
        =link_to "- Abandonar" , "/theories/#{@adoption.theory.id}/abandon",  :data => { :confirm => 'Tem certeza?' }
        =paginate @journals

app/views/adoptions/new.html.haml
.userNew
  .data
    .greetings
      %h1 Nova Adoção
    %p#notice= notice
    .content
      = render 'form'

app/views/adoptions/show.html.haml
.tableArea
  .data#admin
    %h1 Adoção
    %p#notice= notice

    %p Theory:
    %h2= "#{@adoption.theory_id}, #{@adoption.theory.title}"

    %p User:
    %h2= "#{@adoption.user_id}, #{@adoption.user.name}"

    = link_to 'Editar', edit_adoption_path(@adoption)
    |
    = link_to 'Voltar', adoptions_path