config/routes.rb
Ideia::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  root to: "index#index"

  resources :journals

  resources :adoptions do
    member do
          get "journal"
    end
   end

  resources :categories do
    member do
      get "theories"
      get "tips"
    end
  end

  resources :admins

  resources :users

  resources :theories do
     member do
          get "adopt"
          get "abandon"
    end
   end

  resources :tips

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  #get
  get 'theories/adopted'
  get 'users/validated'
  get 'index/index'
  get 'index/about'
  get 'users/message_return'
  get 'login/login'
  get 'login/logout'
  #post
  post 'login/login'
  post 'login/logout'
  post 'register/new'
  post '/vote/:theory_id/:vote' => 'votes#vote'
  post '/favorite/:theory_id/' => 'favorites#check'
  post '/votes/:tip_id/:vote' => 'votes#tipv'
  post '/favorites/:tip_id/' => 'favorites#tipf'
  post '/theories/search' => 'theories#search'

  match 'entrar' => 'login#login'
  match 'sair' => 'login#logout'
  match '/users/:token/confirm' => 'users#confirm'
  match '/users/:id/send' => 'users#sendMail'
  match '/adoptions/new/:theory' => 'adoptions#new'
  match '/journals/new/:id' => 'journals#new'
  match '*a', to: 'errors#routing'

end

app/models/theory.rb
#encoding: utf-8
class Theory < ActiveRecord::Base
  include ImageSaver
  attr_accessible :brief, :choice, :description, :justification, :outlay, :title, :kind, :user_id, :view, :image_title, :data_stream, :category_ids
        #validates
        validates  :title, length: {maximum: 100}, format:{with: /^[a-zA-ZçÇà-úÀ-Ú ]+$/}
        validates_presence_of :outlay, :brief, :description, :justification, :title
        validates_numericality_of :outlay
        validates_length_of :brief, minimum: 50, maximum: 255
        validates_length_of :description, :justification, minimum: 50
        #relations
        belongs_to :user
        has_many :adoptions,  dependent: :destroy
        has_one :image, as: :imageable,  dependent: :destroy
        has_and_belongs_to_many :categories
        has_many :votes,  dependent: :destroy
        has_many :favorites,  dependent: :destroy
        accepts_nested_attributes_for :categories, allow_destroy: true, reject_if: proc{|attrs| attrs['id'].blank?}

  def inc_view
    self.view = self.view ? self.view+1 : 0
  end

  def adopted_by?(user_id)
    adoptions.where(user_id: user_id)
  end

  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, conditions: ['title LIKE ? OR description LIKE ? OR justification LIKE ? OR brief LIKE ?', search_condition, search_condition, search_condition, search_condition])
  end

end

app/controllers/theories_controller.rb
# encoding: utf-8
class TheoriesController < ApplicationController
  layout 'empty'
  require "user"
  respond_to :html
  before_filter :logged? , :except => [:show]
  before_filter :tested_adoption?, only: [:adopt]
  before_filter :tested_abandon?, only: [:abandon]

  def index
    @theories = Theory.all
    @categories = Category.all
    respond_with @theory, @categories
  end

  def show
    @theory = Theory.find(params[:id]) rescue nil
    if @theory
      @theory.inc_view
      @theory.save
      respond_with @theory
    else
      redirect_to "/404"
    end
  end

  def new
    if session[:tested] || admin_session?
      @theory = Theory.new
      @users = User.find(:all)
      respond_with @theory
    else
      flash[:notice] = "Você se cadastrou mas ainda não confirmou seu cadastro."
      redirect_to "/users/#{session[:id]}"
    end
  end

  def edit
    @theory = Theory.find(params[:id]) rescue nil
    if @theory
      if @theory.user.id == session[:id] || admin_session?
        @theory = Theory.find(params[:id])
        respond_with @theory
      else
        flash[:notice] = "Essa historia não é de sua propriedade, então voce não pode altera-la"
        redirect_to "/"
      end
    else
      redirect_to "/404"
    end
  end

  def create
   if admin_session?
      @theory = Theory.new(params[:theory])
      flash[:notice] = "Ideia criada com sucesso!" if @theory.save
      respond_with @theory
      return
    end

   if session[:tested] && !admin_session?
      @theory = current_user.theories.new(params[:theory])
      flash[:notice] = "Ideia criada com sucesso!" if @theory.save

      if !@theory.categories.first
        @theory.category_ids = Category.find(6).id
        @theory.save
      end

      respond_with @theory
    else
      flash[:notice] = "Você esta cadastrado mas ainda não esta confirmado."
      redirect_to "/users/#{session[:id]}"
    end
  end

  def user_admin_find
    User.find(params[:id])
  end

  def update
     if session[:tested] || admin_session?
        params[:theory][:category_ids] ||= []
        @theory = Theory.find(params[:id])
        flash[:notice] = "Dados da ideia atualizados com sucesso." if @theory.update_attributes(params[:theory])
        if !@theory.categories.first
          @theory.category_ids = Category.find(6).id
          @theory.save
        end

        respond_with @theory
      else
         flash[:notice] = "Você esta cadastrado mas ainda não esta confirmado."
          redirect_to "/users/#{session[:id]}"
      end
  end

  def destroy
    @theory = Theory.find(params[:id])
    if admin_session? || session[:id] == @theory.user.id
      flash[:notice] = "Infelizmente a ideia foi apagada." if @theory.destroy
      redirect_to "/theories"
    else
      flash[:notice] = "Você não pode apagar uma idea que não te pertence."
      redirect_to "/theories"
    end
  end

  def search
    @search = params[:search]
    @theories = Theory.search params[:search]
  end

  def adopt
    @theory = Theory.find( params[:id] ) rescue nil
      if !@theory
        redirect_to "/404"
        return
      end

      if @theory.choice == true || @theory.user == current_user
        if @theory.adopted_by?(session[:id]).size>0
          flash[:notice] = "Opa! Você já adotou esta ideia!"
          redirect_to "/users/#{session[:id]}"
          return
        end

        Adoption.create(theory_id: @theory.id,user_id: session[:id])
        redirect_to "/theories/adopted"
      else
        flash[:notice] = "Desculpe, mas o dono da ideia, deseja deixa-la privada."
        redirect_to user_path(session[:id])
      end
  end

def abandon
    @theory = Theory.find( params[:id] ) rescue nil
    if !@theory
      redirect_to "/404"
      return
    end

    @adoption = @theory.adopted_by?(session[:id])
    if @adoption.size<1
      flash[:notice] = "Opa! você não adotou esta ideia!"
      redirect_to "/users/#{session[:id]}"
      return
    end

    @adoption.first.journals.delete_all if @adoption.first.journals
    @adoption.first.destroy
    flash[:notice] = "Ficamos tristes quando alguem desiste, obrigado por tentar !"
    redirect_to "/theories"
end

  private
  def tested?
    if !session[:tested]
      flash[:notice] = "Você esta cadastrado mas ainda não confirmou seu perfil."
      redirect_to admin_session? ? "/" : "/users/#{session[:id]}"
    end
  end

  def tested_adoption?
    if admin_session?
      flash[:notice] = "Opa! Uma administrador infelizmente não pode adotar uma ideia!"
      redirect_to "/"
      return
    end
    tested?
  end

  def tested_abandon?
    if admin_session?
      flash[:notice] = "Opa! Uma administrador não possui adoções para abandonar!"
      redirect_to "/"
      return
    end
    tested?
  end
end

app/views/theories/_doar.html.haml
%form{ target: 'pagseguro', action: 'https://pagseguro.uol.com.br/checkout/v2/donation.html', method: 'post' }
  %input{ type: 'hidden', name: 'receiverEmail', value: "#{@theory.user.email}" }
  %input{ type: 'hidden', name: 'currency', value: 'BRL'}
  %input{name: "submit", src: "/images/120x53-doar.png", type: "image"}

app/views/theories/_errors.html.haml
-if @theory.errors.any?
  #error_explanation
    %h2
      = "Algo não me deixou salvar esta ideia."
      %br
      = "Não esqueça de colocar a imagen Novamente."
    %ul
      - @theory.errors.full_messages.each do |msg|
        #erros= msg

app/views/theories/_facebook.html.haml
.fb-comments{"data-href" => "http://ideas.com/theories/#{@theory.id}", "data-width" => "500", "num_posts" => "5"}

app/views/theories/_favorites.html.haml
= @theory.favorites.count

app/views/theories/_form.html.haml
.formContent
  .inputs
    = form_for(@theory, :html =>{:multipart => true}) do |f|
      =render 'theories/errors'
      -if params[:user]
        = hidden_field_tag :user_id, params[:user]
      .data
        -if session[:kind] == 2
          .adminField
            %p#label Selecione o Usuário
            = f.collection_select :user_id, User.all, :id , :name, name: 'theory[user_id]'
        .field
          %p#label= f.label :title
          = f.text_field :title, class: 'textinput', maxlength: 100
        .field
          %p#label= f.label :description
          = f.text_area :description, class: "redactor"
        .field
          %p#label= f.label :justification
          = f.text_area :justification, class: "redactor"
        .field
          %p#label= f.label :brief
          = f.text_area :brief, maxlength: 255, class: 'brief'
      .options
        .field
          %p#label= f.label :outlay
          = f.text_field :outlay, class: 'textinput'
        .choice
          %p Como as pessoas podem te ajudar?
          = f.select(:choice, options_for_select([['Desenvolvendo minha ideia', true], ['Me financiando.', false]]))
        .kind
          %p Todos podem adotar sua idea?
          = f.select(:kind, options_for_select([['Sim', true], ['Não', false]]))
        .categories
          %p#categoryTitle Selecione as categorias que sua ideia se encaixa.
          = f.collection_select :category_ids, Category.all, :id , :title, {multiple: true}, name: 'theory[category_ids][]'
          = f.collection_select :category_ids, Category.all, :id , :title, {multiple: true}, name: 'theory[category_ids][]'
          = f.collection_select :category_ids, Category.all, :id , :title, {multiple: true}, name: 'theory[category_ids][]'

        = render 'shared/image_field', f: f
        =f.submit class: 'enter'

app/views/theories/_googleplus.html.haml
.g-plus{"data-action" => "share", "data-annotation" => "vertical-bubble", "data-height" => "60"}

app/views/theories/_like.html.haml
.fb-like{"data-href" => "http://ideas.com/theories/#{@theory.id}", "data-layout" => "box_count", "data-send" => "true", "data-show-faces" => "true", "data-width" => "60"}

app/views/theories/_reddit.html.haml
%script{:src => "http://www.reddit.com/static/button/button3.js", :type => "text/javascript"}

app/views/theories/adopted.html.haml
%h1{align: "center"}
  Parabéns e Obrigado!
%h2{align: "center" }
  Você acaba de adotar uma ideia, agora você possui algumas resposabilidades.
.AdoptList
  %h3
    %dl
      %dt
        Fazer um historico:
      %dd
        º Procure fazer upload de imagens com o progresso da ideia.
      %dd
        º Descreva os processos, que foram feitos no progresso do projeto.
      %dd
        º Procure ser o mais técnico possivel.
      %dt
        Divirta-se fazendo o projeto!!
.clear

app/views/theories/edit.html.haml
.editIdea
  %section#introduction
    %h1 Atualizar dados.
    %p
      %h2 Toda ideia é valida, coloque suas melhores ideias.
  .form
    = render 'form'

app/views/theories/index.html.haml
%p#notice= notice
#content
  %h1 Ideias!
  -if session[:kind] == 2
    .adminPanel
      .buttons
        .button
          =link_to "+Idea!", new_theory_path, class: "navlinks"
  %p Procure dentre os mais variados tipos de ideias!
  .categories
    .category
      -@categories.each do |category|
        =link_to "#{category.title}", "/categories/#{category.id}/theories", class: "category"
  .boxes
    -@theories.each do |theory|
      .box
        %h1= link_to truncate(theory.title, length: 15, separator:' ').humanize , theory if theory
        .imageTheory
          -if theory.image
            %img.logo{src: "#{theory.image.to_s}"}
          -else
            %img{alt: "#{theory.title}", src: "/assets/no-image-found.jpg"}
        .dataTheory
          %p#author= link_to "Por: #{truncate(theory.user.name, length: 20, separator:' ').titleize}", "/users/#{theory.user.id}" if theory
          %p#views
            %span
              %img{src: "/assets/category.png"}
              = link_to theory.categories.first.title, "/categories/#{theory.categories.first.id}/theories"

app/views/theories/new.html.haml
.newIdea
  %section#introduction
    %h1 Hora de pensar!
    %p
      %h2 Toda ideia é valida, coloque suas melhores ideias.
    %p
      %h2 Quando mais concisa for sua ideia, mais chances você tem de se tornar ganhar famoso e ganhar mais doações ou visualizaçoes. Caso alguma empresa goste da sua idea, novas oportunidades vão surgir.
  = render 'form'
  .hints
    %section
      %h1#hintTitle Como ter uma boa ideia?
      %h2 Título
      %p Expresse o títuto como um resumo geral da sua ideia, acrescentando o nome do projeto se existir. Você tem 100 caracteres para isto.

      %h2 Descrição
      %p A descrição da sua idea, serve para apresentar e explicar como funciona o seu projeto. Procure ser tecnico. Deixe o texto bem formatado e com facilidade para o entendimento.

      %h2 Justificativa
      %p Apresente problemas que a seu projeto vem a solucionar, e também mostre a real necessidade da sua ideia.

      %h2 Resumo
      %p O resumo, é o texto que o usuário encontra logo de cara, seja no indice ou na pagina da sua ideia. Procure explicar tudo do seu projeto, o que ele faz, pra que serve. Você tem 255 caracteres para isto.

      %h2 Gastos
      %p Mostre para o expectador o valor que seu projeto precisa para ser executado. Muitos usuarios olham este valor no primeiro momento.(Preencha apenas com números)

app/views/theories/search.html.haml
.searchResult
  -if @theories.first
    %h1= "Sua busca por \" <span class='found'>#{truncate(@search, length: 60, separator:' ').humanize}</span> \" retornou:".html_safe
    .stripIndex
      -@theories.each do |theory|
        .strip
          .stripImg
            %a{href: "/theories/#{theory.id}"}
              -if theory.image
                %img{alt: "#{theory.title}", src: "#{theory.image.to_s}"}
              -else
                %img{alt: "#{theory.title}", src: "/assets/no-image-found.jpg"}
          .stripContent
            .contentTitle
              =link_to truncate(theory.title, length: 15, separator:' ').titleize, "/theories/#{theory.id}"
            .contentBrief
              =truncate(theory.brief, length: 120, separator:' ').humanize
            .contentCategory
              =theory.categories.first.title if theory.categories.first
              ="Outros" if !theory.categories.first
          .endStrip
  -else
    .searchResult
      %h1= "Sua busca por \" <span class='error'>#{truncate(@search, length: 60, separator:' ').humanize}</span>  \" não retornou nenhum resultado;".html_safe
      %h2 Tente se lembrar do título ou descrição da idea.
    .searchAgain
      =render 'layouts/search'
    = content_for :javascript do
      :javascript
        new RemoveInput()

app/views/theories/show.html.haml
%p#notice= notice
.masterBox{'data-id' => @theory.id}
  .data
    .presentation
      .content#presentation
        .image
          .logoTheory
            %img{:src => "#{@theory.image.to_s}"}
          .votes
            .vote#up
              #count
                .point= @theory.votes.where(point: true).count
            .vote#down
              #count
                .point= @theory.votes.where(point: false).count
          .favorite
            = render 'theories/favorites'
          .donation
            -if @theory.kind
              =render 'doar'
        .brief
          %p#title= @theory.title
          %p#author
            Por:
            =link_to @theory.user.name, @theory.user
          %p#brief= @theory.brief
          %p#adopte=link_to "ADOTE ESTA IDEIA!", adopt_theory_path(@theory) if @theory.choice?
    .content
      %p
        %h2 O que é?
        = raw @theory.description
      %p
        %h2 E porque precisamos?
        = raw @theory.justification
      %p
        %h2 Quanto isso vai custar?
        %h1=number_to_currency(@theory.outlay, unit: "R$")
  -if @theory.adoptions.first
    .adoptions
      %p
        %h2 Usuarios que adotaram:
      .users
        -@theory.adoptions.each do |adoption|
          .user
            %a{href: "/users/#{adoption.user.id}"}
              -if adoption.user.image
                .image
                  %img#adopter{alt: "#{adoption.user.name}", src: "#{adoption.user.image.to_s}"}
              -else
                .image
                  %img#adopter{alt: "#{adoption.user.name}", src: "/assets/no-image-found.jpg"}

  -if @theory.user.id == session[:id] || session[:kind] == 2
    .adminPanel
      .buttons
        .button
          = link_to 'Atualizar dados', edit_theory_path(@theory)
        .button
          = link_to 'Apagar', @theory, method: :delete, data: { confirm: 'Are you sure?' }
  .socialPlugins
    .links
      .like=render 'theories/like'
      .google=render 'theories/googleplus'
      .reddit=render 'theories/reddit'
      .twitter=render 'theories/twitter'
      .facebook=render 'theories/facebook'

= content_for :javascript do
  :javascript
    new Votes()
    new Favorite()