config/routes.rb
Ideia::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  root to: "index#index"

  resources :journals

  resources :adoptions do
    member do
          get "journal"
    end
   end

  resources :categories do
    member do
      get "theories"
      get "tips"
    end
  end

  resources :admins

  resources :users

  resources :theories do
     member do
          get "adopt"
          get "abandon"
    end
   end

  resources :tips

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  #get
  get 'theories/adopted'
  get 'users/validated'
  get 'index/index'
  get 'index/about'
  get 'users/message_return'
  get 'login/login'
  get 'login/logout'
  #post
  post 'login/login'
  post 'login/logout'
  post 'register/new'
  post '/vote/:theory_id/:vote' => 'votes#vote'
  post '/favorite/:theory_id/' => 'favorites#check'
  post '/votes/:tip_id/:vote' => 'votes#tipv'
  post '/favorites/:tip_id/' => 'favorites#tipf'
  post '/theories/search' => 'theories#search'

  match 'entrar' => 'login#login'
  match 'sair' => 'login#logout'
  match '/users/:token/confirm' => 'users#confirm'
  match '/users/:id/send' => 'users#sendMail'
  match '/adoptions/new/:theory' => 'adoptions#new'
  match '/journals/new/:id' => 'journals#new'
  match '*a', to: 'errors#routing'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :theory_id
  has_and_belongs_to_many :theories

  default_scope order ("title")

  validates :title, presence: true, length: {maximum:30}, format: {with: /^[a-zA-Z ]+$/}
  accepts_nested_attributes_for :theories, allow_destroy: true
end

app/controllers/categories_controller.rb
#encoding: utf-8
class CategoriesController < ApplicationController
 layout 'empty'
 respond_to 'html'

 before_filter :logged?
 before_filter :admin?, except: [:theories]

  def index
    @categories = Category.all
    respond_with :html
  end

  def show
    @category = Category.find(params[:id]) rescue nil
    if @category
      respond_with @category
    else
      redirect_to "/404"
    end
  end

  def new
    @category = Category.new
    respond_with @category
  end

  def edit
    @category = Category.find(params[:id]) rescue nil
    if @category
      respond_with @category
    else
      redirect_to "/404"
    end
  end

  def create
    @category = Category.new(params[:category])
    flash[:notice]="Cateroria criada com sucesso!" if @category.save
    respond_with @category
  end

  def update
    @category = Category.find(params[:id])
    flash[:notice] = "Atualizada com sucesso !" if @category.update_attributes(params[:category])
    respond_with @category
  end

  def theories
    @category = Category.find(params[:id]) rescue nil
    if @category
      @theories = @category.theories
    else
      redirect_to "/404"
    end
  end

  def tips
    @category = Category.find(params[:id]) rescue nil
    if @category
      @tips = @category.tips
    else
      redirect_to "/404"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_with @category
  end
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %ul
        - @category.errors.full_messages.each do |msg|
          #erros= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Salvar', class: 'enter'

app/views/categories/edit.html.haml
.userNew
  .data
    .greetings
      %h2 Atualização de categoria!
    %p#notice= notice
    .content
      = render 'form'

app/views/categories/index.html.haml
.tableArea
  .data
    %h1 Categorias
    .adminPanel
      .buttons
        .button
          = link_to 'Nova Categoria', new_category_path
    %table.tables
      %thead
        %tr
          %th Titulo
          %th Ideias nesta categoria
          %th
          %th
      %tbody
        - @categories.each do |category|
          %tr
            %td= category.title
            %td= category.theories.count
            %td= link_to 'Editar', edit_category_path(category)
            %td= link_to 'Apagar', category, :method => :delete, :data => { :confirm => 'Certeza?' }

app/views/categories/new.html.haml
.userNew
  .data
    .greetings
      %h1 Nova Categoria
    %p#notice= notice
    .content
      = render 'form'

app/views/categories/show.html.haml
.tableArea
  .data#admin
    %h1 Categoria
    %p#notice= notice

    %p Título:
    %h2= @category.title
    %p Ideias:
    %h2= "#{@category.theories.count}, nesta categoria."


    = link_to 'Editar', edit_category_path(@category)
    |
    = link_to 'Voltar', adoptions_path

app/views/categories/theories.html.haml
%p#notice= notice
#content
  %h1=@category.title
  -if session[:kind] == 2
    .adminPanel
      .buttons
        .button
          =link_to "+Idea!", new_theory_path
  %p Procure dentre os mais variados tipos de ideias!"
  .boxes
    -@theories.each do |theory|
      .box
        %h1= link_to truncate(theory.title, length: 15, separator:' ').humanize , theory if theory
        .imageTheory
          -if theory.image
            %img.logo{src: "#{theory.image.to_s}"}
          -else
            %img{alt: "#{theory.title}", src: "/assets/no-image-found.jpg"}
        .dataTheory
          %p#author= link_to "Por: #{truncate(theory.user.name, length: 20, separator:' ').titleize}", "/users/#{theory.user.id}" if theory
          %p#views
            %span
              %img{src: "/assets/category.png"}
              = link_to theory.categories.first.title, "/categories/#{theory.categories.first.id}/theories"