config/routes.rb
Ideia::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  root to: "index#index"

  resources :journals

  resources :adoptions do
    member do
          get "journal"
    end
   end

  resources :categories do
    member do
      get "theories"
      get "tips"
    end
  end

  resources :admins

  resources :users

  resources :theories do
     member do
          get "adopt"
          get "abandon"
    end
   end

  resources :tips

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  #get
  get 'theories/adopted'
  get 'users/validated'
  get 'index/index'
  get 'index/about'
  get 'users/message_return'
  get 'login/login'
  get 'login/logout'
  #post
  post 'login/login'
  post 'login/logout'
  post 'register/new'
  post '/vote/:theory_id/:vote' => 'votes#vote'
  post '/favorite/:theory_id/' => 'favorites#check'
  post '/votes/:tip_id/:vote' => 'votes#tipv'
  post '/favorites/:tip_id/' => 'favorites#tipf'
  post '/theories/search' => 'theories#search'

  match 'entrar' => 'login#login'
  match 'sair' => 'login#logout'
  match '/users/:token/confirm' => 'users#confirm'
  match '/users/:id/send' => 'users#sendMail'
  match '/adoptions/new/:theory' => 'adoptions#new'
  match '/journals/new/:id' => 'journals#new'
  match '*a', to: 'errors#routing'

end

app/views/layouts/_admin.html.haml
=link_to "Dicas", tips_path, class: "navlinks"
=link_to "Admins", admins_path, class: "navlinks"
=link_to "Ideias", theories_path, class: "navlinks"
=link_to "Adoções", adoptions_path, class: "navlinks"
=link_to "Diarios", journals_path, class: "navlinks"
=link_to "Usuários", users_path, class: "navlinks"
=link_to "Categorias", categories_path, class: "navlinks"
=link_to "Sair", "/sair", id: "logout"

app/views/layouts/_footer.html.haml
.contentFooter
  Lucas lindo

app/views/layouts/_search.html.haml
=form_tag controller: 'theories', action: 'search', method: 'get' do
  =text_field_tag :search, params[:search], id: 'search', autocomplete: "off"

app/views/layouts/_user.html.haml
=link_to "Perfil", User.find(session[:id]), class: "navlinks"
=link_to "+Idea!", new_theory_path, class: "navlinks"
=link_to "+Dica!", new_tip_path, class: "navlinks"
=link_to "Ideias", theories_path, class: "navlinks"
=link_to "Dicas", tips_path, class: "navlinks"
=link_to "Sair", "/sair", id: "logout", class: "navlinks"

app/views/layouts/_visitor.html.haml
=link_to "Login", "/entrar", class: "navlinks"
=link_to "Cadastrar", "/users/new", class: "navlinks"

app/views/layouts/empty.html.haml
!!!
%html
  %head
    %title Idea - Onde sua idea cria asas.
    = stylesheet_link_tag "empty", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
      .headerContent
        .logo
          = link_to image_tag( '/assets/ideas.png'), '/', id: 'logo'
        %nav
          - if session[:kind] == 2
            = render "layouts/admin"
          - else
            -if session[:kind] == 1
              = render "layouts/user"
            -else
              = render "layouts/visitor"
        -if session[:kind] == 1
          .search
            =render 'layouts/search'
    .section#main
      = yield
      = yield :javascript
    #footer
      =render 'layouts/footer'